'use strict';
// No analytics provider loads automatically. A consented integration can consume
// these events; field values, phone numbers and emails are never included.
function track(name,detail={}){window.dispatchEvent(new CustomEvent('flowagent:conversion',{detail:{event:name,...detail}}));if(window.flowagentAnalyticsConsent===true&&typeof window.gtag==='function')window.gtag('event',name,detail);}
const toggle=document.querySelector('.mobile-toggle'),nav=document.getElementById('mainNav');
toggle?.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(open));nav.classList.toggle('is-open',open);});
document.addEventListener('click',event=>{const a=event.target.closest('a');if(!a)return;const u=new URL(a.href,location.href);if(u.hostname==='wa.me')track('whatsapp_click');else if(u.pathname==='/demo')track('demo_click');else if(u.pathname==='/contact')track('audit_click');else if(/calendly|cal\.com/.test(u.hostname))track('book_call_click');});
const conversations={delivery:['Do you deliver to Marrakech?','Yes, our sample shop delivers to Marrakech. Which product are you interested in?','The blue backpack.','What name should our team use when following up?'],lead:['I would like a quote.','Of course. What service are you interested in?','Office cleaning, twice a week.','What is your name and business location? I can pass those details to the team.'],human:['I need to talk to a person.','I can flag this conversation for the team. What would you like help with?','An issue with my order.','Please share your order reference. The team can review your request and follow up.']};
document.querySelectorAll('[data-demo]').forEach(button=>button.addEventListener('click',()=>{const box=document.getElementById('demoConversation');box.replaceChildren(...conversations[button.dataset.demo].map((text,i)=>{const p=document.createElement('p');p.className='bubble '+(i%2?'assistant':'customer');p.textContent=text;return p;}));document.querySelectorAll('[data-demo]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));track('demo_click',{scenario:button.dataset.demo});}));
const form=document.getElementById('auditForm');
form?.addEventListener('focusin',()=>track('form_start'),{once:true});
form?.addEventListener('submit',async event=>{event.preventDefault();const button=form.querySelector('button[type=submit]'),status=document.getElementById('auditStatus');button.disabled=true;status.textContent='Sending your request…';try{const data=Object.fromEntries(new FormData(form));const response=await fetch('/api/forms/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw Error(result.error||'Your request could not be saved. Please try again.');status.textContent='Your request is saved. We will follow up using the contact details you provided. A call is not booked yet.';track('form_submit');form.reset();}catch(error){status.textContent=error.message;}finally{button.disabled=false;}});
