'use strict';
const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function articleHtml(v){return String(v||'').replace(/<(script|style|iframe)[\s\S]*?<\/\1>/gi,'').replace(/<[^>]*>/g,t=>/^<\/?(?:p|h2|h3|ul|ol|li|strong|em|blockquote|br)\s*\/?>$/i.test(t)?t:'');}
const aliases={'shopify-seo-blog-automation':'blog-automation'};
const slug=s=>aliases[s.slug]||s.slug;
const contentSlugs=['blog-automation','social-media-automation','social-media-manager','ai-video'];
const link=s=>'/services/'+slug(s);
const list=items=>`<ul>${(items||[]).map(x=>`<li>${e(x)}</li>`).join('')}</ul>`;
const safe=v=>/^https:\/\//i.test(v||'')||/^\/(?!\/)/.test(v||'')?e(v):'/contact';
const button=(text='Request a free audit',href='/contact',secondary=false)=>`<a class="btn ${secondary?'btn-secondary':'btn-primary'}" href="${safe(href)}">${e(text)}</a>`;
const section=(title,body,id='')=>`<section class="section" ${id?`id="${id}"`:''}><div class="container"><h2>${e(title)}</h2>${body}</div></section>`;
const faq=items=>(items||[]).map(x=>`<details><summary>${e(x.question)}</summary><p>${e(x.answer)}</p></details>`).join('');
const cards=items=>`<div class="marketing-grid">${items.map(s=>`<article class="service-card"><p class="eyebrow">${e(s.category||'BUSINESS AUTOMATION')}</p><h3><a href="${link(s)}">${e(s.title)}</a></h3><p>${e(s.description)}</p><a class="text-link" href="${link(s)}">Explore the service →</a></article>`).join('')}</div>`;
const intro=(title,text,extra='')=>`<section class="marketing-hero"><div class="container"><p class="eyebrow">FLOWAGENT · BUSINESS AUTOMATION</p><h1>${e(title)}</h1><p class="hero-text">${e(text)}</p>${extra}</div></section>`;
const process=()=>section('A clear path from idea to launch',`<ol class="marketing-steps"><li><strong>01 · Review</strong><p>Map one repeated task, its volume and the tools you use.</p></li><li><strong>02 · Build</strong><p>Connect approved information and define what needs human approval.</p></li><li><strong>03 · Test</strong><p>Check normal requests, missing information and handoff before launch.</p></li><li><strong>04 · Support</strong><p>Agree who monitors the workflow and how changes are handled.</p></li></ol>`);
const demo=()=>`<div class="marketing-demo"><div><p class="eyebrow">ILLUSTRATIVE DEMO · SAMPLE DATA</p><h2>A question becomes a useful enquiry.</h2><p>See how a business assistant could answer, collect details, or hand a conversation to your team. This is a scripted example, not a live WhatsApp connection or a client result.</p><div class="demo-options"><button type="button" data-demo="delivery">Delivery question</button><button type="button" data-demo="lead">Capture a lead</button><button type="button" data-demo="human">Human handoff</button></div></div><div class="demo-phone" aria-live="polite"><p class="eyebrow">EXAMPLE SHOP · WHATSAPP ASSISTANT</p><div id="demoConversation"><p class="bubble customer">Do you deliver to Marrakech?</p><p class="bubble assistant">Yes, our sample shop delivers to Marrakech. Which product are you interested in?</p><p class="bubble customer">The blue backpack.</p><p class="bubble assistant">What name should our team use when following up?</p></div><small>Answers use the business information you approve.</small></div></div>`;
function header(d){return `<a class="skip-link" href="#main">Skip to content</a><div class="container header-inner"><a class="brand" href="/"><img class="flowagent-brand-logo" src="${safe('/'+(d.settings.logoPath||'flowagent-logo.png').replace(/^\//,''))}" width="64" height="64" alt="${e(d.settings.brandName||'FlowAgent')}"><span class="brand-text">${e(d.settings.brandName||'FlowAgent')}</span></a><button type="button" class="mobile-toggle" aria-expanded="false" aria-controls="mainNav" aria-label="Open navigation">☰</button><nav class="nav-links" id="mainNav" aria-label="Main navigation"><a href="/services">Services</a><a href="/demo">Demo</a><a href="/pricing">Pricing</a><a href="/about">About</a><a href="/contact" class="btn btn-primary btn-sm">Free audit</a></nav></div>`;}
function footer(d){return `<div class="container marketing-footer"><div><strong>${e(d.settings.brandName||'FlowAgent')}</strong><p>WhatsApp assistants and practical business automation.</p></div><nav aria-label="Footer navigation"><a href="/services">All services</a><a href="/content">Content automation</a><a href="/contact">Contact</a><a href="/faq">FAQ</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a></nav><p>© ${new Date().getFullYear()} FlowAgent</p></div>`;}
function contact(d){const c=d.pageContent.contact;return intro(c.headline,c.intro)+section('Tell us where enquiries get stuck',`<div class="marketing-contact"><form id="auditForm" class="glass-card" method="post" action="/api/forms/contact"><label>Your name<input name="name" required maxlength="120" autocomplete="name"></label><label>Business name<input name="company" required maxlength="160" autocomplete="organization"></label><label>Email<input type="email" name="email" required maxlength="254" autocomplete="email"></label><label>Phone / WhatsApp (optional)<input name="phone" maxlength="60" autocomplete="tel"></label><label>Website or Instagram (optional)<input name="website" maxlength="300"></label><label>Country<input name="country" required maxlength="100" autocomplete="country-name"></label><label>Approximate WhatsApp enquiries per month<select name="volume"><option>Not sure yet</option>Under 100</option><option>100–500</option><option>500–2,000</option><option>More than 2,000</option></select></label><label>What do customers ask, and what happens after they message you?<textarea name="message" required rows="5" maxlength="5000"></textarea></label><input type="hidden" name="service" value="WhatsApp automation audit"><label class="consent"><input type="checkbox" required> I agree to be contacted about this request. <a href="/privacy">Privacy policy</a></label><button class="btn btn-primary" type="submit">Request my free audit</button><p id="auditStatus" role="status" aria-live="polite"></p><noscript><p>The form saves your request and returns a confirmation page.</p></noscript></form><aside><h3>What happens next?</h3><p>We review your current process and reply to arrange a 20-minute conversation. You leave with a suggested first workflow and the next steps.</p><p>No payment is required to request the audit. This form requests a conversation; it does not reserve a calendar slot.</p>${d.settings.businessEmail?`<p>Email: <a href="mailto:${e(d.settings.businessEmail)}">${e(d.settings.businessEmail)}</a></p>`:''}${d.settings.whatsapp?button('Message on WhatsApp','https://wa.me/'+String(d.settings.whatsapp).replace(/\D/g,''),true):''}${/^https:\/\//.test(d.settings.bookingLink||'')?`<p>${button('Choose a call time',d.settings.bookingLink,true)}</p>`:''}</aside></div>`);}
function render(d,path,info){const services=d.services.filter(s=>!s.legacy);const h=d.pageContent.home;let body;
 if(path==='/')body=intro(h.heroTitle,h.heroText,`<div class="marketing-actions">${button(h.primaryCtaLabel,h.primaryCtaLink)}${button('See the example','/demo',true)}</div><p class="small-note">Start with one workflow. Agree the scope before you commit.</p>`)+section('From the first message to the next step',`<ol class="marketing-flow"><li>Customer enquiry</li><li>WhatsApp assistant</li><li>Answers & details</li><li>Your sheet or CRM</li><li>Your team</li></ol>`)+section('See the conversation',demo(),'demo')+section('Three ways to take work off your plate',cards(['whatsapp-chat-bot','lead-generation','custom-n8n-automation'].map(x=>services.find(s=>s.slug===x)).filter(Boolean))+`<p class="marketing-actions">${button('Explore all services','/services',true)}</p>`,'servicesSection')+process()+section('Built around your existing tools','<p>WhatsApp · Google Sheets · Your CRM · Your calendar · Email</p><p>We confirm the access and integrations your workflow needs during the audit. You approve the source information and the point where your team takes over.</p>')+section('Know what you are buying',`<p>A defined workflow, clear deliverables, a test checklist and a handoff. Review example requests and agree on support before launch.</p>${button('See scope and pricing','/pricing',true)}`)+section('Questions before you start',faq(d.faqs.filter(f=>['faq-001','faq-scope','faq-human','faq-security'].includes(f.id))))+section(h.finalCtaTitle,`<p>${e(h.finalCtaText)}</p>${button(h.finalCtaLabel,h.finalCtaLink)}`);
 else if(info.service){const s=info.service;body=intro(s.title,s.description,button(s.slug==='social-media-manager'?'Discuss availability':'Request a free audit','/contact?service='+encodeURIComponent(slug(s))))+section('Who this is for',`<p>${e(s.audience||'Businesses looking to automate a defined, repeated task.')}</p>`)+section('What is included',list(s.deliverables))+section('How the workflow works',`<ol>${(s.workflowSteps||s.useCases||[]).map(x=>`<li>${e(x)}</li>`).join('')}</ol>`)+section('Scope and next steps',`<p>${e(s.price||'Scoped quote')} · We confirm integrations, monthly volume, approval steps and support before work begins.</p>${button('Compare engagement options','/pricing',true)}`)+(s.faq?.length?section('Frequently asked questions',faq(s.faq)):'')+section('Related services',cards(services.filter(x=>x.id!==s.id&&!contentSlugs.includes(slug(x))).slice(0,3)));}
 else if(path==='/services'||path==='/content')body=intro(path==='/content'?'Content creation & publishing workflows':'Business automation services',path==='/content'?'Connect content ideas, review and publishing. Each channel and generation tool is confirmed before setup.':'Start with WhatsApp enquiries, lead follow-up or one repeated business task. Explore the full catalogue below.')+section(path==='/content'?'Content services':'Customer conversations & operations',cards(services.filter(s=>path==='/content'?contentSlugs.includes(slug(s)):!contentSlugs.includes(slug(s)))))+(path==='/services'?section('Looking for content automation?',`<p>Blog, video and social publishing workflows have their own collection.</p>${button('Explore content services','/content',true)}`):'');
 else if(path==='/demo')body=intro('See a WhatsApp assistant conversation','Explore three examples before discussing your own workflow.')+section('A simple, transparent example',demo())+section('Want to test your own questions?',`<p>Send us your business type and typical enquiries. We can discuss a demo based on your approved information.</p>${button()}`);
 else if(path==='/contact')body=contact(d);
 else if(path==='/pricing')body=intro('Start small. Know the scope.','Review the workflow first, then choose the implementation and support you need.')+section('01 · Free discovery audit',`<p>A 20-minute discussion of your current process, the tools involved, and a practical first use case. No payment required.</p>${button()}`)+section('02 · Implementation options',`<div class="marketing-grid">${d.pricingPlans.filter(p=>!p.legacy).map(p=>`<article class="package-card"><h3>${e(p.name)}</h3><p class="marketing-price">${e(p.price)}</p><p>${e(p.summary)}</p>${list(p.features)}${button('Discuss this scope','/contact?plan='+encodeURIComponent(p.id))}</article>`).join('')}</div><p class="small-note">The listed plans cover the agreed workflow and volume, not unlimited usage. We confirm monthly limits and any separately quoted work in writing before payment.</p>`)+section('03 · Management & support','<p>Confirm monitoring, maintenance, response expectations and change requests in your proposal. Additional integrations or higher volume may need a separate quote.</p>');
 else if(path==='/about'){const a=d.pageContent.about;body=intro(a.headline,a.intro)+section('How we approach your project',`<p>${e(a.mission)}</p><p>${e(a.whyAi)}</p>${list(a.methodology)}`)+process()+section('Talk through your business',`<p>Work starts with your real questions and source material. You review the workflow before launch.</p>${button()}`);}
 else if(path==='/faq')body=intro(d.pageContent.faq.headline,d.pageContent.faq.intro)+section('Your questions, answered',faq(d.faqs));
 else if(path==='/case-studies')body=intro('Workflow examples','Illustrative implementation patterns. These are not verified client results.')+section('From an enquiry to a follow-up',demo())+section('More workflow examples',d.caseStudies.map(c=>`<article><h3>${e(c.title)}</h3><p>${e(c.solution)}</p></article>`).join(''));
 else if(path==='/testimonials')body=intro('Customer feedback','Verified customer testimonials will be published here when available.')+section('Explore the service first',`<p>Use the sample conversation to understand the approach, then ask about your own use case.</p>${button('See the example','/demo')}`);
 else if(path==='/blog')body=intro(d.pageContent.blog.headline,d.pageContent.blog.intro)+section('Articles',`<div class="marketing-grid">${d.blogPosts.map(p=>`<article class="blog-card"><h3><a href="/blog/${e(p.slug)}">${e(p.title)}</a></h3><p>${e(p.excerpt)}</p></article>`).join('')}</div>`);
 else if(info.post){const p=info.post;body=intro(p.title,p.excerpt)+section('Article',articleHtml(p.contentHtml)||String(p.body||p.content||'').split(/\n\s*\n/).map(x=>`<p>${e(x)}</p>`).join(''));}
 else if(path==='/privacy')body=intro('Privacy notice','How website enquiries are handled. Updated 12 September 2026.')+section('Information you provide','<p>The enquiry form collects your name, email, business details, optional phone number and website, country, approximate message volume and the message you enter. We use these details to review and respond to your request.</p>')+section('Storage and service providers','<p>Enquiries are saved in the website administration system. The website uses Render hosting and, when configured, Supabase storage. If form email notifications are configured, the enquiry is also sent through the notification provider. Access to the administration system requires authentication.</p>')+section('Analytics and cookies','<p>This website update does not enable advertising pixels or third-party analytics. Administrator sign-in uses a session cookie. Any future analytics or advertising integration should be disclosed before it is enabled.</p>')+section('Your choices',`<p>To ask about your data or request correction or deletion, contact <a href="mailto:${e(d.settings.businessEmail)}">${e(d.settings.businessEmail)}</a>. Do not submit passwords, payment card details or sensitive customer records in the enquiry form.</p>`)+section('Client automation data','<p>Data access, service providers and retention for a client automation are agreed separately before implementation. This notice describes the website enquiry process.</p>');
 else if(path==='/terms')body=intro('Service terms','The written project proposal defines the work you purchase.')+section('Scope and payment','<p>Submitting an enquiry or requesting an audit does not purchase a service. Before paid work starts, we confirm deliverables, connected tools, message or content volume, price, payment schedule and support in writing. Monthly packages apply to the agreed workflow and volume.</p>')+section('Access, testing and approval','<p>You provide the business information and necessary account permissions. The workflow is tested against the agreed scope before launch. Additional integrations, changes or higher volume are discussed separately.</p>')+section('Results and ongoing service','<p>Search rankings, views, sales and uninterrupted third-party platform availability are not guaranteed. AI output can require review. Cancellation, refund arrangements and maintenance responsibilities are confirmed in the written agreement before payment.</p>')+section('Questions',`<p>Contact <a href="mailto:${e(d.settings.businessEmail)}">${e(d.settings.businessEmail)}</a> before purchasing if anything in the scope is unclear.</p>`);
 return body===undefined?null:body;
}
module.exports={render,header,footer,aliases,slug,link};
