const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');
const {createStudio,providerInput}=require('../studio-backend.cjs');
async function fixture(t,fetchImpl){const directory=await fs.mkdtemp(path.join(os.tmpdir(),'flowagent-test-'));t.after(()=>fs.rm(directory,{recursive:true,force:true}));const env={KIE_API_KEY:'test',REPLICATE_API_TOKEN:'test',FLOWAGENT_WORKER_TOKEN:'test-secret'};const studio=createStudio({directory,env,fetchImpl,verifySession:req=>req.auth===true,parseJsonBody:async req=>req.body,sendJson:(res,status,data)=>Object.assign(res,{status,data})});async function call(route='',method='GET',body={},auth=true,headers={}){const req={method,body,auth,headers:{host:'localhost:4180','content-type':'application/json',...headers},socket:{remoteAddress:'127.0.0.1'}};const res={setHeader(){}};await studio.handle(req,res,'/api/studio'+route,{baseUrl:'http://localhost:4180',sessionSecret:'test'});return res.data;}return {studio,call,env};}
const brief={name:'Test brand',description:'Soap made in Casablanca',language:'English'};const draft={plan:'starter',kind:'video',channel:'instagram',prompt:'Show the soap on a table',caption:'Our new soap'};
test('private workspace and worker reject unauthenticated requests',async t=>{const {call}=await fixture(t);await assert.rejects(call('','GET',{},false),{statusCode:401});await assert.rejects(call('/worker/tick','POST',{},false),{statusCode:401});await assert.rejects(call('/brand','PUT',brief,true,{origin:'https://evil.example'}),{statusCode:403});});
test('brief/draft persistence, duplicate prevention, worker completion and approval',async t=>{const calls=[];const {call,studio}=await fixture(t,async(url,options)=>{calls.push({url,options});return {ok:true,json:async()=>url.includes('createTask')?{code:200,data:{taskId:'kie-test'}}:{code:200,data:{state:'success',resultJson:JSON.stringify({resultUrls:['https://cdn.example.com/output.mp4']})}}};});await call('/brand','PUT',brief);const {post}=await call('/posts','POST',draft);assert.equal((await studio.read()).posts.length,1);await call('/posts/'+post.id+'/generate','POST');await assert.rejects(call('/posts/'+post.id+'/generate','POST'),{statusCode:409});await studio.tick();assert.equal(calls.length,1);assert.equal(JSON.parse(calls[0].options.body).input.duration,'10');await studio.tick();assert.equal((await studio.read()).posts[0].status,'review');await call('/posts/'+post.id+'/approve','POST');assert.equal((await studio.read()).posts[0].status,'approved');await studio.tick();assert.equal(calls.length,2);});
test('ambiguous provider submission is held and never automatically charged again',async t=>{let attempts=0;const {call,studio}=await fixture(t,async()=>{attempts++;throw new Error('network timeout');});await call('/brand','PUT',brief);const {post}=await call('/posts','POST',draft);await call('/posts/'+post.id+'/generate','POST');await studio.tick();await studio.tick();assert.equal(attempts,1);assert.equal((await studio.read()).posts[0].status,'needs_attention');});
test('validation rejects image Shorts, missing brief and unsafe references',async t=>{const {call}=await fixture(t);await assert.rejects(call('/posts','POST',draft),{statusCode:400});await call('/brand','PUT',brief);await assert.rejects(call('/posts','POST',{...draft,kind:'image',channel:'youtube'}),{statusCode:400});await assert.rejects(call('/posts','POST',{...draft,referenceImage:'http://localhost/private'}),{statusCode:400});});
test('provider settings match the selected package',()=>{const base={...draft,brand:brief};assert.equal(providerInput(base).model,'google/gemini-omni-flash-1-1');const premium=providerInput({...base,plan:'premium',referenceImage:'https://cdn.example.com/product.png'});assert.equal(premium.input.duration,20);assert.equal(premium.provider,'replicate');assert.deepEqual(premium.input.reference_images,['https://cdn.example.com/product.png']);assert.equal(providerInput({...base,kind:'image'}).model,'google/nano-banana-2');});
test('missing keys block generation while preserving the draft',async t=>{const {call,studio,env}=await fixture(t);delete env.KIE_API_KEY;await call('/brand','PUT',brief);const {post}=await call('/posts','POST',draft);await assert.rejects(call('/posts/'+post.id+'/generate','POST'),{statusCode:503});assert.equal((await studio.read()).posts[0].status,'draft');});
