'use strict';
const fs=require('node:fs/promises');
const path=require('node:path');
const crypto=require('node:crypto');
const plans={starter:{model:'google/gemini-omni-flash-1-1',provider:'kie',duration:10},premium:{model:'bytedance/seedance-2.5',provider:'replicate',duration:20}};
function fail(message,statusCode=400){throw Object.assign(new Error(message),{statusCode});}
function clean(value,max=1000){return String(value??'').trim().slice(0,max);}
function publicUrl(value){if(!value)return '';let url;try{url=new URL(value);}catch{fail('Enter a valid HTTPS image URL.');}if(url.protocol!=='https:'||url.username||url.password||url.hostname==='localhost'||!url.hostname.includes('.')||/^(127\.|10\.|192\.168\.|169\.254\.|172\.(1[6-9]|2\d|3[01])\.)/.test(url.hostname)||url.hostname.includes(':'))fail('Use a publicly accessible HTTPS URL.');return url.href;}
function safeEqual(a,b){return typeof a==='string'&&typeof b==='string'&&Buffer.byteLength(a)===Buffer.byteLength(b)&&crypto.timingSafeEqual(Buffer.from(a),Buffer.from(b));}
function providerInput(post){const prompt=`Business: ${post.brand.name}. ${post.brand.description}\nAudience: ${post.brand.audience}. Language: ${post.brand.language}. Tone: ${post.brand.tone}.\nCreative direction: ${post.prompt}\nUse only the product claims supplied above. Preserve reference product appearance.`;if(post.kind==='image')return {provider:'replicate',model:'google/nano-banana-2',input:{prompt,aspect_ratio:'4:5',output_format:'png',...(post.referenceImage?{image_input:[post.referenceImage]}:{})}};const plan=plans[post.plan];return {provider:plan.provider,model:plan.model,input:plan.provider==='kie'?{prompt,duration:'10',aspect_ratio:'9:16',resolution:'720p',...(post.referenceImage?{image_urls:[post.referenceImage]}:{})}:{prompt,duration:20,aspect_ratio:'9:16',resolution:'720p',generate_audio:true,...(post.referenceImage?{reference_images:[post.referenceImage]}:{})}};}
function createStudio({directory,documentStore,env=process.env,fetchImpl=fetch,verifySession,parseJsonBody,sendJson}){
 const storePath=path.join(env.FLOWAGENT_DATA_DIR||path.join(directory,'data'),'studio-private.json');let serial=Promise.resolve();let ticking=false;
 async function read(){if(documentStore){const state=await documentStore.read('studio');if(state)return state;return {version:1,brand:{name:'',description:'',audience:'',language:'English',tone:'Direct and friendly',knowledge:''},posts:[],workerLastSeen:null};}try{return JSON.parse(await fs.readFile(storePath,'utf8'));}catch(error){if(error.code!=='ENOENT')throw error;return {version:1,brand:{name:'',description:'',audience:'',language:'English',tone:'Direct and friendly',knowledge:''},posts:[],workerLastSeen:null};}}
 function change(fn){const result=serial.then(async()=>{const state=await read();const value=await fn(state);if(documentStore){await documentStore.write("studio",state);return value;}await fs.mkdir(path.dirname(storePath),{recursive:true});const temp=storePath+'.tmp';await fs.writeFile(temp,JSON.stringify(state,null,2),{mode:0o600});await fs.rename(temp,storePath);return value;});serial=result.catch(()=>{});return result;}
 function connections(){return {'Gemini Omni':Boolean(env.KIE_API_KEY),'Seedance & images':Boolean(env.REPLICATE_API_TOKEN),'n8n worker':Boolean(env.FLOWAGENT_WORKER_TOKEN),'Instagram':false,'Facebook':false,'YouTube':false};}
 async function request(url,options={}){const response=await fetchImpl(url,{...options,signal:AbortSignal.timeout(25000)});const data=await response.json();if(!response.ok)throw new Error(`Provider request failed (${response.status}). Check provider dashboard before retrying.`);return data;}
 async function submit(post){const spec=providerInput(post);if(spec.provider==='kie'){const data=await request('https://api.kie.ai/api/v1/jobs/createTask',{method:'POST',headers:{Authorization:`Bearer ${env.KIE_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:spec.model,input:spec.input})});if(data.code!==200||!data.data?.taskId)throw new Error('Kie did not confirm a task. Check its dashboard before retrying.');return {provider:'kie',providerId:data.data.taskId};}const data=await request(`https://api.replicate.com/v1/models/${spec.model}/predictions`,{method:'POST',headers:{Authorization:`Bearer ${env.REPLICATE_API_TOKEN}`,'Content-Type':'application/json'},body:JSON.stringify({input:spec.input})});if(!data.id)throw new Error('Replicate did not confirm a task. Check its dashboard before retrying.');return {provider:'replicate',providerId:data.id};}
 async function poll(post){if(post.provider==='kie'){const data=await request('https://api.kie.ai/api/v1/jobs/recordInfo?taskId='+encodeURIComponent(post.providerId),{headers:{Authorization:`Bearer ${env.KIE_API_KEY}`}});if(data.code!==200)throw new Error('Unable to check Kie task.');if(data.data?.state==='fail')return {status:'failed',error:'Generation failed. Review the provider dashboard.'};if(data.data?.state!=='success')return null;const result=JSON.parse(data.data.resultJson||'{}');return {status:'review',assetUrl:publicUrl(result.resultUrls?.[0])};}const data=await request('https://api.replicate.com/v1/predictions/'+encodeURIComponent(post.providerId),{headers:{Authorization:`Bearer ${env.REPLICATE_API_TOKEN}`}});if(['failed','canceled'].includes(data.status))return {status:'failed',error:'Generation failed or was canceled. Review the provider dashboard.'};if(data.status!=='succeeded')return null;return {status:'review',assetUrl:publicUrl(Array.isArray(data.output)?data.output[0]:data.output)};}
 async function tick(){if(ticking)return {busy:true};ticking=true;let processed=0;try{const jobs=await change(state=>{state.workerLastSeen=new Date().toISOString();for(const post of state.posts){if(post.status==='submitting'&&Date.now()-Date.parse(post.updatedAt)>120000){post.status='needs_attention';post.error='Submission was interrupted. Check the provider dashboard before creating another generation.';}}return state.posts.filter(p=>p.status==='queued'||p.status==='generating').slice(0,3).map(p=>({...p}));});for(const post of jobs){try{if(post.status==='queued'){await change(state=>{const p=state.posts.find(p=>p.id===post.id);p.status='submitting';p.updatedAt=new Date().toISOString();});const result=await submit(post);await change(state=>Object.assign(state.posts.find(p=>p.id===post.id),result,{status:'generating',updatedAt:new Date().toISOString()}));}else{const result=await poll(post);if(result){if(result.status==='review'&&!result.assetUrl)throw new Error('Provider returned no output URL.');await change(state=>Object.assign(state.posts.find(p=>p.id===post.id),result,{updatedAt:new Date().toISOString()}));}}processed++;}catch(error){await change(state=>{const p=state.posts.find(p=>p.id===post.id);if(post.status==='queued')p.status='needs_attention';p.error=error.message;p.updatedAt=new Date().toISOString();});}}return {processed};}finally{ticking=false;}}
 async function handle(req,res,pathname,config){if(!pathname.startsWith('/api/studio'))return false;res.setHeader('Cache-Control','no-store');
  if(pathname==='/api/studio/worker/tick'){if(req.method!=='POST')fail('Method not allowed',405);if(!env.FLOWAGENT_WORKER_TOKEN||!safeEqual(req.headers.authorization,'Bearer '+env.FLOWAGENT_WORKER_TOKEN))fail('Unauthorized',401);sendJson(res,200,await tick());return true;}
  const local=env.FLOWAGENT_LOCAL_STUDIO==='1'&&env.HOST==='127.0.0.1'&&['127.0.0.1','::1','::ffff:127.0.0.1'].includes(req.socket.remoteAddress)&&['localhost','127.0.0.1'].includes(new URL('http://'+req.headers.host).hostname);
  if(!local&&!(config.sessionSecret&&verifySession(req,config)))fail('Unauthorized',401);
  if(req.method!=='GET'){const origin=req.headers.origin;if(origin){const expected=local?`http://${req.headers.host}`:new URL(config.baseUrl).origin;if(origin!==expected)fail('Origin not allowed',403);}if(!String(req.headers['content-type']).startsWith('application/json'))fail('JSON required',415);}
  if(req.method==='GET'&&pathname==='/api/studio'){const state=await read();sendJson(res,200,{...state,connections:connections(),plans});return true;}
  if(req.method==='PUT'&&pathname==='/api/studio/brand'){const body=await parseJsonBody(req,16000);if(!clean(body.name)||!clean(body.description))fail('Business name and description are required.');const brand={name:clean(body.name,100),description:clean(body.description,2000),audience:clean(body.audience,300),language:clean(body.language,80)||'English',tone:clean(body.tone,100),knowledge:clean(body.knowledge,5000)};await change(state=>{state.brand=brand;});sendJson(res,200,{brand});return true;}
  if(req.method==='POST'&&pathname==='/api/studio/posts'){const body=await parseJsonBody(req,12000);if(!plans[body.plan]||!['image','video'].includes(body.kind)||!['instagram','facebook','youtube'].includes(body.channel))fail('Choose a supported package, format and channel.');if(body.kind==='image'&&body.channel==='youtube')fail('YouTube Shorts requires a video.');if(!clean(body.prompt))fail('Add a creative direction.');const post=await change(state=>{if(!state.brand.name)fail('Save your brand brief first.');if(state.posts.length>=500)fail('Pilot workspace limit reached.',409);const p={id:crypto.randomUUID(),plan:body.plan,kind:body.kind,channel:body.channel,prompt:clean(body.prompt,3000),caption:clean(body.caption,2200),referenceImage:publicUrl(body.referenceImage),brand:{...state.brand},status:'draft',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};state.posts.push(p);return p;});sendJson(res,201,{post});return true;}
  const match=pathname.match(/^\/api\/studio\/posts\/([\w-]+)\/(generate|approve|reject)$/);
  if(req.method==='POST'&&match){const post=await change(state=>{const p=state.posts.find(p=>p.id===match[1]);if(!p)fail('Post not found',404);if(match[2]==='generate'){if(p.status!=='draft')fail('This post has already been queued or generated.',409);const provider=providerInput(p).provider;if(!env.FLOWAGENT_WORKER_TOKEN||!(provider==='kie'?env.KIE_API_KEY:env.REPLICATE_API_TOKEN))fail('Connect n8n and the generation provider before generating.',503);const month=new Date().toISOString().slice(0,7);const count=state.posts.filter(x=>x.kind===p.kind&&x.generatedAt?.startsWith(month)).length;if(count>=30)fail('The monthly pilot allowance of 30 generations for this format is used.',409);p.status='queued';p.generatedAt=new Date().toISOString();}else{if(p.status!=='review')fail('Only completed content awaiting review can be approved or rejected.',409);p.status=match[2]==='approve'?'approved':'rejected';}p.updatedAt=new Date().toISOString();return p;});sendJson(res,200,{post});return true;}
  fail('Not found',404);
 }
 return {handle,tick,read,providerInput};
}
module.exports={createStudio,providerInput,publicUrl,plans};
